### ISSUE TITLE
pcall may panic on arm osx since commit d4a554d

### ISSUE THREAD

**Issue by fastcoding** [LuaJIT/LuaJIT#698]
On Apple silicon machine, starting from commit d4a554d6ee1507f7313641b26ed09bf1b518fa1f,  

```lua
pcall(require, 'any-non-exist-module') 
```

results in :

```text
PANIC: unprotected error in call to Lua API (module 'any-non-exist-module' not found...
```
It looks like xcflags: LUAJIT_UNWIND_EXTERNAL causes this issue and should be removed on m1 machine:

```diff
diff --git a/src/Makefile b/src/Makefile
index fdf04b6e..42c879d8 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -319,7 +319,9 @@ ifeq (Darwin,$(TARGET_SYS))
     $(error missing: export MACOSX_DEPLOYMENT_TARGET=XX.YY)
   endif
   TARGET_STRIP+= -x
+  ifneq (arm64,$(shell uname -m))
   TARGET_XCFLAGS+= -DLUAJIT_UNWIND_EXTERNAL
+  endif
   TARGET_XSHLDFLAGS= -dynamiclib -single_module -undefined dynamic_lookup -fPIC
   TARGET_DYNXLDOPTS=
   TARGET_XSHLDFLAGS+= -install_name $(TARGET_DYLIBPATH) -compatibility_version $(MAJVER).$(MINVER) -current_version $(MAJVER).$(MINVER).$(RELVER)
```

**Comment by MikePall** [comment]
OSX should be capable of external unwinding on all architectures. The toolchain generates unwind info on ARM64, too. So there must be some other problem.

Since I'm not using Apple gear, somebody else needs to contribute a fix.

**Comment by MikePall** [comment]
I just noticed the ARM64 interpreter doesn't have unwind info for the Mach-O assembler output format. Here's a [potential fix](https://gist.github.com/MikePall/768ea114f9d20c04fe992d0b96408066).

Please try to apply this diff and report back. Maybe the personality handler reference `_lj_err_unwind_dwarf@GOTPCREL` needs to be modified to make it work.

**Comment by fastcoding** [comment]
Assembler reports error after applied the [potential fix](https://gist.github.com/MikePall/768ea114f9d20c04fe992d0b96408066):

```text
...
lj_vm.S:16177:1: error: assembler local symbol 'LEFDE159' not defined
lj_vm.S:16177:1: error: assembler local symbol 'LSCIEX' not defined
...
```

I tried adding a dot before LEFDE%d and LSCIEX label in the fixed codes to make assembler happy, but the linker ld report another error:

```
ld: malformed __eh_frame section: FDE points to CIE outside __eh_frame section file 'lj_vm.o'
```

**Comment by MikePall** [comment]
Thanks! OK, [next try](https://gist.github.com/MikePall/a8ed2d7f0918aa012a92d4992caab043). Apply to the original.

**Comment by fastcoding** [comment]
Same result:

```text
...
ld: warning: could not create compact unwind for _lj_vm_exit_handler: registers 78 not saved contiguously in frame
ld: warning: could not create compact unwind for _lj_vm_exit_interp: registers 78 not saved contiguously in frame
ld: warning: could not create compact unwind for _lj_vm_modi: registers 78 not saved contiguously in frame
ld: warning: could not create compact unwind for _lj_vm_ffi_callback: registers 78 not saved contiguously in frame
ld: warning: could not create compact unwind for _lj_cont_ffi_callback: registers 78 not saved contiguously in frame
ld: warning: could not create compact unwind for _lj_vm_ffi_call: register 20 saved somewhere other than in frame
Undefined symbols for architecture arm64:
  "ltmp0", referenced from:
      Dwarf Exception Unwind Info (__eh_frame) in libluajit.a(lj_vm.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [luajit] Error 1

```

**Comment by MikePall** [comment]
Oh well. This is getting complicated. Thank you for your patience! But unwind handling is all guesswork, because it's barely documented.

After reshuffling the stack frame layout, I think the warnings about compact unwind info should be gone now.

But I don't know where `ltmp0` is coming from. There's no such label in `lj_vm.S`. Maybe this is a side-effect of the use of `@GOTPCREL`? But then I don't know how the reference to the personality routine can be formulated for Mach-O/ARM64.

Anyway, [here's my last attempt](https://gist.github.com/MikePall/f6bb3e09a11826a339574f49d895e82c) for now.

**Comment by igormunkin** [comment]
@MikePall, I've tried the last patch: the same issue with `ltmp0` and the bunch of warnings from ld regarding compact unwind. So, I've decided to share [the artefacts](https://gist.github.com/igormunkin/483d05680c04f1ac9be63529d0001730). Looks like `ltmp0` should be `_lj_BC_ISLT`, but I'm not sure.

**Comment by fastcoding** [comment]
Unfortunately,  it's still the same result - both warnings and errors.
The *ltmp0* symbol appears in every compiled object file, which should be produced by clang.

```shell
src % gobjdump -T luajit.o |grep ltmp
00000000 l       0e SECT   01 0000 [.text] ltmp0
00001308 l       0e SECT   02 0000 [.const] ltmp1
00001370 l       0e SECT   03 0000 [.cstring] ltmp2
00001ac0 l       0e SECT   04 0000 [.bss] ltmp3
00001720 l       0e SECT   05 0000 [.data] ltmp4
00001728 l       0e SECT   06 0000 [__LD.__compact_unwind] ltmp5
000018a8 l       0e SECT   07 0000 [.eh_frame] ltmp6

src % gobjdump -T lj_vm.o | grep ltmp
00000000 l       0e SECT   01 0000 [.text] ltmp0
00003d3c l       0e SECT   02 0000 [.cstring] ltmp1
00003d50 l       0e SECT   03 0000 [.eh_frame] ltmp2
```
Thanks a lot for your help. This let me learn more about luajit internals.

However, this issue is not urgent because my previous patch( the one removes -DLUAJIT_UNWIND_EXTERNAL from XCFLAGS) works quite well on my m1 machine - no compile issue, no pcall panic and the variadic args issue is gone as well.

**Comment by criemen** [comment]
@MikePall Would donating you an M1 mac facilitate debugging and addressing this issue?

**Comment by MikePall** [comment]
No, not at all. This issue needs help from someone with very deep knowledge about macOS and MACH-O/DWARF stack unwinding internals, i.e. not me.

**Comment by clason** [comment]
I'm very sorry, but https://github.com/LuaJIT/LuaJIT/commit/421c4c798791d27b7f967df39891c4e4fa1d107c seems to have broken the build on Apple ARM (macOS 11.6, clang-12.0.5) again. The previous commit builds fine, but after this I get the dreaded
```
Undefined symbols for architecture arm64:
  "ltmp0", referenced from:
      Dwarf Exception Unwind Info (__eh_frame) in libluajit.a(lj_vm.o)
ld: symbol(s) not found for architecture arm64
```
Let me know if there is more info I can provide.

**Comment by MikePall** [comment]
OK, now it's fully disabled.

**Comment by clason** [comment]
Yep, now it builds correctly. Thank you very much!

**Comment by MikePall** [comment]
Fixed by #757.
